name: Test

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: [Deploy]
    types: completed

jobs:
  test:
    runs-on: arc-runners
    steps:
      - name: Test step
        run: |
          echo "Testing..."