name: Test ARC Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: arc-runners
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test environment
      run: |
        echo "Running on a self-hosted runner"
        echo "Runner name: ${{ runner.name }}"
        echo "Runner OS: ${{ runner.os }}"

    - name: Test docker in docker 
      run: |
        docker version
        docker info
        docker run --rm ubuntu:latest bash -c "echo hello Google DevFest 2024"
