name: Test ARC Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: arc-runners
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test environment
      run: |
        echo "Running on a self-hosted runner"
        echo "Runner name: ${{ runner.name }}"
        echo "Runner OS: ${{ runner.os }}"

    - name: Test docker in docker 
      run: |
        docker run --rm ubuntu:latest bash -c "echo hello Google DevFest 2024"
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)